# Generated by Django 3.2.8 on 2021-10-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexx', '0004_alter_user_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[(' ', ' '), ('ativo', 'ativo'), ('inativo', 'inativo')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
