# Generated by Django 3.2.8 on 2021-10-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexx', '0005_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('nao definido', 'nao definido'), ('ativo', 'ativo'), ('inativo', 'inativo')], default='nao definido', max_length=20),
        ),
    ]
