# Generated by Django 3.2.8 on 2021-10-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexx', '0006_alter_user_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Bot',
        ),
    ]
