# Generated by Django 3.2.8 on 2021-10-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexx', '0007_rename_user_bot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Habilidade',
        ),
        migrations.AlterModelTable(
            name='habilidade',
            table='Habilidadizinha',
        ),
    ]
