# Generated by Django 3.2.8 on 2021-10-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexx', '0008_auto_20211030_0353'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bot',
            table=None,
        ),
        migrations.AlterModelTable(
            name='habilidade',
            table=None,
        ),
    ]
