# Generated by Django 3.2.8 on 2021-10-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexx', '0009_auto_20211030_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='habilidade',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='habilidade',
            old_name='usuario',
            new_name='portador',
        ),
        migrations.AlterField(
            model_name='bot',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('nulo', 'nulo'), ('ativo', 'ativo'), ('inativo', 'inativo')], default='nulo', max_length=20),
        ),
    ]
