# Generated by Django 3.2.8 on 2021-10-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexx', '0010_auto_20211030_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='status',
            field=models.CharField(choices=[('nulo', 'nulo'), ('ativo', 'ativo'), ('inativo', 'inativo')], default='nulo', max_length=20),
        ),
    ]
