# Generated by Django 3.2.8 on 2021-10-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexx', '0011_habilidade_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidade',
            options={'verbose_name_plural': 'Habilidades'},
        ),
    ]
