# Generated by Django 3.2.8 on 2021-10-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexx', '0012_alter_habilidade_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilidade',
            new_name='Habilidades',
        ),
    ]
